debug_gatt:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: taelek
    steps:
      required: true
      selector:
        object:
    sync_time:
      default: true
      selector:
        boolean:
